# Generated by Django 5.2.8 on 2025-12-02 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("bio", models.TextField(blank=True)),
                ("profile_image_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
                "db_table": "staff_members",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StaffService",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_staff",
                        to="services.service",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_services",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Service",
                "verbose_name_plural": "Staff Services",
                "db_table": "staff_services",
            },
        ),
        migrations.AddField(
            model_name="staffmember",
            name="services",
            field=models.ManyToManyField(
                related_name="staff_members", through="staff.StaffService", to="services.service"
            ),
        ),
        migrations.AddIndex(
            model_name="staffservice",
            index=models.Index(
                fields=["service", "is_primary"], name="staff_servi_service_e6d010_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staffservice",
            unique_together={("staff_member", "service")},
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(fields=["shop", "is_active"], name="staff_membe_shop_id_4e1762_idx"),
        ),
    ]
