# Generated by Django 5.2.8 on 2025-12-09 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_service_buffer_minutes"),
        ("shops", "0003_shop_timezone"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmember",
            name="clerk_invitation_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="invite_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="invite_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="invite_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("accepted", "Accepted"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(fields=["email"], name="staff_membe_email_734491_idx"),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(fields=["invite_status"], name="staff_membe_invite__41d137_idx"),
        ),
    ]
