# Generated by Django 5.2.8 on 2025-12-22 12:00

import apps.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[apps.core.validators.validate_phone_number],
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("unpaid", "Unpaid"),
                            ("trialing", "Trialing"),
                        ],
                        default="trialing",
                        max_length=20,
                    ),
                ),
                ("subscription_plan", models.CharField(blank=True, max_length=50)),
                ("subscription_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "favorite_shops",
                    models.ManyToManyField(
                        blank=True, related_name="favorited_by", to="shops.shop"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customers",
            },
        ),
    ]
