# Generated by Django 5.2.8 on 2025-12-23 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("services", "0001_initial"),
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "user_role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("client", "Shop Owner"),
                            ("staff", "Staff"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary of older messages for context management",
                    ),
                ),
                ("message_count", models.IntegerField(default=0)),
                ("total_tokens_used", models.IntegerField(default=0)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional session data (device, IP, user agent, etc.)",
                    ),
                ),
                (
                    "current_shop",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shop being discussed in this session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to="shops.shop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "db_table": "agent_chat_sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "AI Assistant"),
                            ("system", "System"),
                            ("tool", "Tool Result"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "tool_calls",
                    models.JSONField(
                        blank=True,
                        help_text="OpenAI tool_calls array if assistant requested tools",
                        null=True,
                    ),
                ),
                (
                    "tool_call_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of tool call this message responds to",
                        max_length=100,
                    ),
                ),
                ("tool_name", models.CharField(blank=True, db_index=True, max_length=100)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                (
                    "openai_request_id",
                    models.CharField(
                        blank=True, help_text="OpenAI API request ID for debugging", max_length=100
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True,
                        help_text="OpenAI model used (e.g., gpt-4-turbo-preview)",
                        max_length=50,
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        default=0, help_text="Time taken to generate response in milliseconds"
                    ),
                ),
                ("is_error", models.BooleanField(db_index=True, default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="agent.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "agent_chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("shop", "Shop"), ("service", "Service"), ("faq", "FAQ")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("pinecone_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("pinecone_namespace", models.CharField(db_index=True, max_length=50)),
                (
                    "content_text",
                    models.TextField(help_text="The text that was embedded and stored"),
                ),
                (
                    "metadata_json",
                    models.JSONField(help_text="Metadata stored with the vector in Pinecone"),
                ),
                ("last_synced_at", models.DateTimeField()),
                ("needs_resync", models.BooleanField(db_index=True, default=False)),
                ("sync_error", models.TextField(blank=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_docs",
                        to="services.service",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_docs",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Document",
                "verbose_name_plural": "Knowledge Documents",
                "db_table": "agent_knowledge_docs",
            },
        ),
        migrations.CreateModel(
            name="AgentAction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("booking_create", "Create Booking"),
                            ("booking_cancel", "Cancel Booking"),
                            ("booking_reschedule", "Reschedule Booking"),
                            ("booking_confirm", "Confirm Booking"),
                            ("booking_complete", "Complete Booking"),
                            ("booking_list", "List Bookings"),
                            ("shop_search", "Search Shops"),
                            ("shop_info", "Get Shop Info"),
                            ("service_list", "List Services"),
                            ("service_info", "Get Service Info"),
                            ("availability_check", "Check Availability"),
                            ("schedule_info", "Get Schedule"),
                            ("staff_list", "List Staff"),
                            ("staff_info", "Get Staff Info"),
                            ("staff_reassign", "Reassign Staff"),
                            ("slot_block", "Block Time Slot"),
                            ("slot_unblock", "Unblock Time Slot"),
                            ("holiday_add", "Add Holiday"),
                            ("stats_query", "Query Statistics"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("input_params", models.JSONField(help_text="Tool input parameters")),
                (
                    "output_result",
                    models.JSONField(blank=True, help_text="Tool output result", null=True),
                ),
                ("success", models.BooleanField(db_index=True, default=True)),
                ("error_message", models.TextField(blank=True)),
                ("execution_time_ms", models.IntegerField(default=0)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_actions",
                        to="bookings.booking",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_actions",
                        to="shops.shop",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="agent.chatmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Action",
                "verbose_name_plural": "Agent Actions",
                "db_table": "agent_actions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action_type", "success"], name="agent_actio_action__e332a7_idx"
                    ),
                    models.Index(fields=["created_at"], name="agent_actio_created_a26aae_idx"),
                    models.Index(
                        fields=["message", "action_type"], name="agent_actio_message_fd74eb_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["user", "is_active"], name="agent_chat__user_id_cf23d3_idx"),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["session_id"], name="agent_chat__session_99bd3d_idx"),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["created_at"], name="agent_chat__created_c2bee7_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="agent_chat__session_a23c63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["role"], name="agent_chat__role_839b5e_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["is_error"], name="agent_chat__is_erro_e87dc0_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(fields=["doc_type", "shop"], name="agent_knowl_doc_typ_66ef65_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(fields=["pinecone_id"], name="agent_knowl_pinecon_d3949f_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(fields=["needs_resync"], name="agent_knowl_needs_r_e3e4b5_idx"),
        ),
    ]
