# Generated by Django 5.2.8 on 2025-12-26 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Unique session identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("ended", "Ended"), ("error", "Error")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_interactions", models.IntegerField(default=0)),
                ("total_duration_seconds", models.IntegerField(default=0)),
                (
                    "openai_session_id",
                    models.CharField(
                        blank=True, help_text="OpenAI Realtime session ID", max_length=100
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice Session",
                "verbose_name_plural": "Voice Sessions",
                "db_table": "voice_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceInteraction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("user_speech", "User Speech"),
                            ("assistant_speech", "Assistant Speech"),
                            ("function_call", "Function Call"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("function_name", models.CharField(blank=True, max_length=100)),
                ("function_args", models.JSONField(blank=True, null=True)),
                ("function_result", models.JSONField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="voice.voicesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice Interaction",
                "verbose_name_plural": "Voice Interactions",
                "db_table": "voice_interactions",
                "ordering": ["created_at"],
            },
        ),
    ]
