# Generated by Django 5.2.8 on 2025-12-30 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
        ("voice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopVoiceAgent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the voice agent is active for this shop"
                    ),
                ),
                (
                    "voice",
                    models.CharField(
                        choices=[
                            ("alloy", "Alloy"),
                            ("echo", "Echo"),
                            ("fable", "Fable"),
                            ("onyx", "Onyx"),
                            ("nova", "Nova"),
                            ("shimmer", "Shimmer"),
                        ],
                        default="alloy",
                        help_text="OpenAI voice for this agent",
                        max_length=50,
                    ),
                ),
                (
                    "custom_greeting",
                    models.TextField(blank=True, help_text="Optional custom greeting message"),
                ),
                (
                    "custom_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Additional instructions for the agent (appended to base prompt)",
                    ),
                ),
                ("total_sessions", models.IntegerField(default=0)),
                ("total_bookings_created", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Shop Voice Agent",
                "verbose_name_plural": "Shop Voice Agents",
                "db_table": "shop_voice_agents",
            },
        ),
        migrations.CreateModel(
            name="VoiceCallLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[("master", "Master Agent"), ("shop", "Shop Agent")],
                        help_text="Agent type that handled this interaction",
                        max_length=20,
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("client", "Client/Owner"),
                            ("staff", "Staff Member"),
                            ("guest", "Guest"),
                        ],
                        default="guest",
                        help_text="User role during this interaction",
                        max_length=20,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("user_speech", "User Speech"),
                            ("assistant_speech", "Assistant Speech"),
                            ("tool_call", "Tool Call"),
                            ("agent_switch", "Agent Switch"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user_input", models.TextField(blank=True, help_text="Transcribed user speech")),
                ("agent_response", models.TextField(blank=True, help_text="Agent response text")),
                (
                    "tool_name",
                    models.CharField(
                        blank=True, help_text="Name of tool called (if any)", max_length=100
                    ),
                ),
                (
                    "tool_input",
                    models.JSONField(blank=True, help_text="Tool input parameters", null=True),
                ),
                (
                    "tool_output",
                    models.JSONField(blank=True, help_text="Tool execution result", null=True),
                ),
                (
                    "tool_success",
                    models.BooleanField(default=True, help_text="Whether tool execution succeeded"),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        default=0, help_text="Time to generate response in milliseconds"
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0, help_text="Tokens consumed for this interaction"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error details if interaction failed"),
                ),
            ],
            options={
                "verbose_name": "Voice Call Log",
                "verbose_name_plural": "Voice Call Logs",
                "db_table": "voice_call_logs",
                "ordering": ["created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="voiceinteraction",
            name="session",
        ),
        migrations.AddField(
            model_name="voicesession",
            name="agent_type",
            field=models.CharField(
                choices=[("master", "Master Agent"), ("shop", "Shop Agent")],
                default="master",
                help_text="Current agent type (master or shop)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="voicesession",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                help_text="Shop for shop agent sessions",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voice_sessions",
                to="shops.shop",
            ),
        ),
        migrations.AddField(
            model_name="voicesession",
            name="total_tokens_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="voicesession",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("client", "Client/Owner"),
                    ("staff", "Staff Member"),
                    ("guest", "Guest"),
                ],
                default="guest",
                help_text="User role for shop agent sessions",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="voicesession",
            index=models.Index(fields=["user", "status"], name="voice_sessi_user_id_d28035_idx"),
        ),
        migrations.AddIndex(
            model_name="voicesession",
            index=models.Index(fields=["shop", "status"], name="voice_sessi_shop_id_8213f9_idx"),
        ),
        migrations.AddIndex(
            model_name="voicesession",
            index=models.Index(
                fields=["agent_type", "status"], name="voice_sessi_agent_t_8994cf_idx"
            ),
        ),
        migrations.AddField(
            model_name="shopvoiceagent",
            name="shop",
            field=models.OneToOneField(
                help_text="The shop this agent belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voice_agent",
                to="shops.shop",
            ),
        ),
        migrations.AddField(
            model_name="voicecalllog",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_logs",
                to="voice.voicesession",
            ),
        ),
        migrations.AddField(
            model_name="voicecalllog",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                help_text="Shop context (for shop agent)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voice_call_logs",
                to="shops.shop",
            ),
        ),
        migrations.DeleteModel(
            name="VoiceInteraction",
        ),
        migrations.AddIndex(
            model_name="voicecalllog",
            index=models.Index(
                fields=["session", "created_at"], name="voice_call__session_c9ca7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voicecalllog",
            index=models.Index(
                fields=["agent_type", "interaction_type"], name="voice_call__agent_t_a19770_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voicecalllog",
            index=models.Index(
                fields=["shop", "created_at"], name="voice_call__shop_id_299aba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voicecalllog",
            index=models.Index(fields=["tool_name"], name="voice_call__tool_na_d6750e_idx"),
        ),
    ]
