# Generated by Django 5.2.8 on 2025-12-22 12:00

import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[apps.core.validators.validate_positive_decimal],
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(validators=[apps.core.validators.validate_duration]),
                ),
                (
                    "buffer_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Minimum time buffer between now and earliest bookable slot (0 = no buffer)",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("image_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("booking_count", models.IntegerField(default=0)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "db_table": "services",
                "ordering": ["-booking_count", "name"],
                "indexes": [
                    models.Index(fields=["shop", "is_active"], name="services_shop_id_6179a7_idx")
                ],
            },
        ),
    ]
