# Generated by Django 5.2.8 on 2025-12-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="buffer_minutes",
            field=models.IntegerField(
                default=15, help_text="Minimum time buffer between now and earliest bookable slot"
            ),
        ),
    ]
