# Generated by Django 5.2.8 on 2026-01-01 12:45

import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[apps.core.validators.validate_positive_decimal],
                    ),
                ),
                ("included_items", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal",
                "verbose_name_plural": "Deals",
                "db_table": "deals",
                "ordering": ["price", "name"],
                "indexes": [
                    models.Index(fields=["shop", "is_active"], name="deals_shop_id_3a13d1_idx")
                ],
            },
        ),
    ]
