# Generated by Django 5.2.8 on 2026-01-02 12:04

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_deal"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="duration_minutes",
            field=models.IntegerField(
                default=60,
                help_text="Duration in minutes for deal booking slots",
                validators=[apps.core.validators.validate_duration],
            ),
        ),
    ]
