# Generated by Django 5.2.8 on 2025-12-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_buffer_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="buffer_minutes",
            field=models.IntegerField(
                default=0,
                help_text="Minimum time buffer between now and earliest bookable slot (0 = no buffer)",
            ),
        ),
    ]
