# Generated by Django 5.2.8 on 2025-12-22 12:00

import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "postal_code",
                    models.CharField(
                        max_length=20, validators=[apps.core.validators.validate_postal_code]
                    ),
                ),
                ("country", models.CharField(default="USA", max_length=100)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20, validators=[apps.core.validators.validate_phone_number]
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("cover_image_url", models.URLField(blank=True)),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Shop timezone (IANA timezone, e.g., Asia/Karachi, Europe/London, America/Los_Angeles)",
                        max_length=63,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_reviews", models.IntegerField(default=0)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop",
                "verbose_name_plural": "Shops",
                "db_table": "shops",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["city", "is_active"], name="shops_city_27230b_idx"),
                    models.Index(fields=["client", "is_active"], name="shops_client__7132bd_idx"),
                ],
            },
        ),
    ]
