# Generated by Django 5.2.8 on 2026-01-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="max_concurrent_deal_bookings",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Maximum number of deal bookings that can happen at the same time slot",
            ),
        ),
    ]
