# Generated by Django 5.2.8 on 2025-12-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_fix_timezone_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Shop timezone (IANA timezone, e.g., Asia/Karachi, Europe/London, America/Los_Angeles)",
                max_length=63,
            ),
        ),
    ]
