# Generated by Django 5.2.8 on 2026-01-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_deal_booking_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="advance_payment_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether customers must pay advance deposit to confirm booking",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="advance_payment_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Percentage of service price required as advance deposit (0-100)",
                max_digits=5,
            ),
        ),
    ]
