# Generated by Django 5.2.8 on 2026-01-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_advance_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="cover_image_url",
            field=models.TextField(
                blank=True,
                help_text="Cover image URL or base64 encoded image. Accepts any string format until GCP bucket is implemented.",
            ),
        ),
    ]
