# Generated by Django 5.2.8 on 2025-12-22 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Plan name (e.g., 'Starter', 'Professional', 'Enterprise')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        help_text="Stripe Price ID (price_xxx)", max_length=255, unique=True
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(help_text="Stripe Product ID (prod_xxx)", max_length=255),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly price in USD (used for tier comparison)",
                        max_digits=10,
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(
                        default="month",
                        help_text="Billing frequency (month or year)",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Plan description for frontend display"),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list, help_text="List of features included in this plan"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether users can subscribe to this plan"
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(default=False, help_text="Show 'Most Popular' badge"),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order for frontend display (lower = higher priority)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "db_table": "subscription_plans",
                "ordering": ["display_order", "amount"],
                "indexes": [
                    models.Index(fields=["stripe_price_id"], name="subscriptio_stripe__86b269_idx"),
                    models.Index(fields=["is_active"], name="subscriptio_is_acti_4d4352_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        help_text="Stripe Subscription ID (sub_xxx)", max_length=255, unique=True
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(help_text="Stripe Customer ID (cus_xxx)", max_length=255),
                ),
                (
                    "stripe_latest_invoice",
                    models.CharField(
                        blank=True, help_text="Latest Stripe Invoice ID (in_xxx)", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_index=True,
                        help_text="Subscription status: active, past_due, canceled, unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is the user's current active subscription",
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(help_text="Current billing period start"),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(help_text="Current billing period end"),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False, help_text="Whether subscription will cancel at period end"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, help_text="When subscription was cancelled", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User (client) who owns this subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Subscription plan tier",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Payment amount in USD", max_digits=10
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        help_text="Payment method type (e.g., 'card', 'bank_account')",
                        max_length=50,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        help_text="Unique transaction identifier", max_length=255, unique=True
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, help_text="Stripe Payment Intent ID (pi_xxx)", max_length=255
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        blank=True, help_text="Stripe Invoice ID (in_xxx)", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_index=True,
                        help_text="Payment status: succeeded, failed, pending, refunded",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateTimeField(help_text="When payment was processed")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional payment data from Stripe"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="Subscription this payment is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payments",
                "ordering": ["-payment_date"],
                "indexes": [
                    models.Index(
                        fields=["subscription", "status"], name="payments_subscri_500936_idx"
                    ),
                    models.Index(fields=["payment_date"], name="payments_payment_aebcb7_idx"),
                    models.Index(fields=["stripe_invoice_id"], name="payments_stripe__63f518_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Action: created, upgraded, downgraded, cancelled, renewed, expired",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, help_text="Reason for the change")),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional data (e.g., Stripe event data)"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the change (if manual)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="The subscription that changed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "new_plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="New plan (for upgrades/downgrades)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "old_plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous plan (for upgrades/downgrades)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription History",
                "verbose_name_plural": "Subscription Histories",
                "db_table": "subscription_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subscription", "action"], name="subscriptio_subscri_d3189a_idx"
                    ),
                    models.Index(fields=["created_at"], name="subscriptio_created_680517_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["user", "status"], name="subscriptio_user_id_8d58fd_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_subscription_id"], name="subscriptio_stripe__aa726e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["is_current"], name="subscriptio_is_curr_ed7b11_idx"),
        ),
    ]
