# Generated by Django 5.2.8 on 2025-12-04 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, help_text="Webhook source: 'stripe' or 'clerk'", max_length=10)),
                ('event_type', models.CharField(db_index=True, help_text="Event type (e.g., 'customer.subscription.created')", max_length=100)),
                ('event_id', models.CharField(help_text='Unique event ID from webhook provider', max_length=255, unique=True)),
                ('payload', models.JSONField(help_text='Full webhook payload (for debugging)')),
                ('processed', models.BooleanField(db_index=True, default=False, help_text='Whether webhook was successfully processed')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of times processing was retried')),
                ('last_retry_at', models.DateTimeField(blank=True, help_text='When last retry attempt was made', null=True)),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'db_table': 'webhook_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'event_type'], name='webhook_log_source_4c9edb_idx'), models.Index(fields=['processed'], name='webhook_log_process_8f7aab_idx'), models.Index(fields=['created_at'], name='webhook_log_created_33987a_idx'), models.Index(fields=['event_id'], name='webhook_log_event_i_41a153_idx')],
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(db_index=True, help_text='Stripe Customer ID (cus_xxx)', max_length=255, unique=True)),
                ('email', models.EmailField(help_text='Email address registered with Stripe', max_length=254)),
                ('default_payment_method', models.CharField(blank=True, help_text='Default payment method ID (pm_xxx)', max_length=255)),
                ('metadata', models.JSONField(default=dict, help_text='Additional data synced from Stripe')),
                ('user', models.OneToOneField(help_text='User this Stripe customer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe Customer',
                'verbose_name_plural': 'Stripe Customers',
                'db_table': 'stripe_customers',
                'indexes': [models.Index(fields=['stripe_customer_id'], name='stripe_cust_stripe__2ea2de_idx'), models.Index(fields=['email'], name='stripe_cust_email_37c97f_idx')],
            },
        ),
    ]
