# Generated by Django 5.2.8 on 2026-01-05 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_advance_payments"),
        ("clients", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectedAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "stripe_account_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stripe Connect Account ID (acct_xxx)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "charges_enabled",
                    models.BooleanField(
                        default=False, help_text="Whether the account can accept charges"
                    ),
                ),
                (
                    "payouts_enabled",
                    models.BooleanField(
                        default=False, help_text="Whether the account can receive payouts"
                    ),
                ),
                (
                    "details_submitted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the owner has submitted all required details",
                    ),
                ),
                (
                    "onboarding_complete",
                    models.BooleanField(
                        default=False, help_text="Whether onboarding is fully complete"
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of business (individual, company)",
                        max_length=50,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Additional data from Stripe account"),
                ),
                (
                    "client",
                    models.OneToOneField(
                        help_text="Client (salon owner) this Connect account belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connected_account",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connected Account",
                "verbose_name_plural": "Connected Accounts",
                "db_table": "connected_accounts",
            },
        ),
        migrations.CreateModel(
            name="BookingPayment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stripe PaymentIntent ID (pi_xxx)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Advance payment amount", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="usd", help_text="Currency code (usd, gbp, etc.)", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not Required"),
                            ("pending", "Payment Pending"),
                            ("paid", "Deposit Paid"),
                            ("refunded", "Refunded"),
                            ("failed", "Payment Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Payment status",
                        max_length=20,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="When payment was confirmed", null=True
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, help_text="When payment was refunded", null=True
                    ),
                ),
                (
                    "stripe_refund_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Refund ID if refunded (re_xxx)",
                        max_length=255,
                    ),
                ),
                ("refund_reason", models.TextField(blank=True, help_text="Reason for refund")),
                ("metadata", models.JSONField(default=dict, help_text="Additional payment data")),
                (
                    "booking",
                    models.OneToOneField(
                        help_text="Booking this payment is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advance_payment",
                        to="bookings.booking",
                    ),
                ),
                (
                    "destination_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Connected account receiving this payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="payments.connectedaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Payment",
                "verbose_name_plural": "Booking Payments",
                "db_table": "booking_payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="connectedaccount",
            index=models.Index(fields=["stripe_account_id"], name="connected_a_stripe__45209f_idx"),
        ),
        migrations.AddIndex(
            model_name="connectedaccount",
            index=models.Index(fields=["charges_enabled"], name="connected_a_charges_d57a12_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingpayment",
            index=models.Index(
                fields=["stripe_payment_intent_id"], name="booking_pay_stripe__3fdedf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingpayment",
            index=models.Index(fields=["status"], name="booking_pay_status_21354b_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingpayment",
            index=models.Index(
                fields=["destination_account", "status"], name="booking_pay_destina_990de3_idx"
            ),
        ),
    ]
