# Generated by Django 5.2.8 on 2026-01-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_advance_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpayment",
            name="payment_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the payment window expires (15 mins after creation)",
                null=True,
            ),
        ),
    ]
