# Generated by Django 5.2.8 on 2026-01-15 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactQuery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="First name of the person", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Last name of the person", max_length=100),
                ),
                ("email", models.EmailField(help_text="Email address for contact", max_length=254)),
                (
                    "phone_number",
                    models.CharField(help_text="Phone number for contact", max_length=20),
                ),
                ("salon_name", models.CharField(help_text="Name of the salon/spa", max_length=255)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("nail_salon", "Nail Salon"),
                            ("day_spa", "Day Spa"),
                            ("hair_salon", "Hair Salon"),
                            ("medical_spa", "Medical Spa"),
                            ("full_service", "Full-Service Beauty Salon"),
                            ("other", "Other"),
                        ],
                        help_text="Type of beauty business",
                        max_length=20,
                    ),
                ),
                (
                    "team_size",
                    models.CharField(
                        choices=[
                            ("1_2", "1-2 team members"),
                            ("3_5", "3-5 team members"),
                            ("6_10", "6-10 team members"),
                            ("11_20", "11-20 team members"),
                            ("20_plus", "20+ team members"),
                        ],
                        help_text="Number of team members",
                        max_length=10,
                    ),
                ),
                (
                    "challenges",
                    models.TextField(
                        help_text="Description of challenges with phone calls and bookings"
                    ),
                ),
                (
                    "best_time_to_reach",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (9 AM - 12 PM)"),
                            ("afternoon", "12 PM - 5 PM"),
                            ("evening", "Evening (5 PM - 8 PM)"),
                            ("anytime", "Anytime"),
                        ],
                        help_text="Best time to reach the person",
                        max_length=10,
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, help_text="Whether the query has been followed up"
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(
                        default=False, help_text="Whether notification email was sent successfully"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal notes for follow-up")),
            ],
            options={
                "verbose_name": "Contact Query",
                "verbose_name_plural": "Contact Queries",
                "db_table": "contact_queries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="contact_que_email_7baee8_idx"),
                    models.Index(fields=["is_processed"], name="contact_que_is_proc_3fa9d0_idx"),
                    models.Index(fields=["created_at"], name="contact_que_created_6aeacc_idx"),
                ],
            },
        ),
    ]
