# Generated by Django 5.2.8 on 2026-01-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_us", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactquery",
            name="team_size",
            field=models.CharField(
                choices=[
                    ("1-2", "1-2 team members"),
                    ("3-5", "3-5 team members"),
                    ("6-10", "6-10 team members"),
                    ("11-20", "11-20 team members"),
                    ("20+", "20+ team members"),
                ],
                help_text="Number of team members",
                max_length=10,
            ),
        ),
    ]
