# Generated by Django 5.2.8 on 2025-12-22 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarIntegration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("google_access_token", models.TextField(blank=True)),
                ("google_refresh_token", models.TextField(blank=True)),
                ("google_token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "google_calendar_id",
                    models.CharField(
                        default="primary",
                        help_text="ID of the Google Calendar to sync events to",
                        max_length=255,
                    ),
                ),
                ("is_sync_enabled", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_integration",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Integration",
                "verbose_name_plural": "Calendar Integrations",
                "db_table": "calendar_integrations",
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("google_event_id", models.CharField(blank=True, max_length=255)),
                ("is_synced", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_error", models.TextField(blank=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="bookings.booking",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="calendars.calendarintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Event",
                "verbose_name_plural": "Calendar Events",
                "db_table": "calendar_events",
                "unique_together": {("booking", "integration")},
            },
        ),
    ]
