# Generated by Django 5.2.8 on 2025-12-16 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_time_slot"),
        ("calendars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_events",
                to="bookings.booking",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="calendarevent",
            unique_together={("booking", "integration")},
        ),
    ]
