# Generated by Django 5.2.8 on 2026-01-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="scraping_count",
            field=models.IntegerField(
                default=0, help_text="Current count of completed scrape jobs"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="scraping_limit",
            field=models.IntegerField(
                default=5, help_text="Maximum number of websites that can be scraped"
            ),
        ),
    ]
