# Generated by Django 5.2.8 on 2025-12-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_update_user_fk_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("unpaid", "Unpaid"),
                    ("trialing", "Trialing"),
                ],
                default="trialing",
                max_length=20,
            ),
        ),
    ]
