# Generated by Django 5.2.8 on 2026-01-13 11:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0004_change_cover_image_to_textfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="WidgetConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("landscape", "Landscape"),
                            ("minimal", "Minimal"),
                        ],
                        default="card",
                        help_text="Widget layout style",
                        max_length=20,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#2563EB",
                        help_text="Primary color in hex format (e.g., #2563EB)",
                        max_length=7,
                    ),
                ),
                (
                    "widget_width",
                    models.PositiveIntegerField(
                        default=380,
                        help_text="Widget width in pixels (280-800)",
                        validators=[
                            django.core.validators.MinValueValidator(280),
                            django.core.validators.MaxValueValidator(800),
                        ],
                    ),
                ),
                (
                    "border_radius",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Border radius in pixels (0-50)",
                        validators=[django.core.validators.MaxValueValidator(50)],
                    ),
                ),
                (
                    "banner_image",
                    models.URLField(
                        blank=True, help_text="Banner image URL (overrides shop cover image)"
                    ),
                ),
                (
                    "custom_title",
                    models.CharField(
                        blank=True,
                        help_text="Custom title (defaults to shop name if empty)",
                        max_length=255,
                    ),
                ),
                (
                    "custom_description",
                    models.TextField(
                        blank=True,
                        help_text="Custom description (defaults to shop description if empty)",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Book Now", help_text="Call-to-action button text", max_length=50
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, help_text="Custom logo URL (overrides shop logo if provided)"
                    ),
                ),
                (
                    "show_logo",
                    models.BooleanField(default=True, help_text="Display logo in widget"),
                ),
                (
                    "text_align",
                    models.CharField(
                        choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                        default="center",
                        help_text="Text alignment for widget content",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Widget is active and can be embedded"
                    ),
                ),
                (
                    "shop",
                    models.OneToOneField(
                        help_text="Shop this widget configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widget_config",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget Configuration",
                "verbose_name_plural": "Widget Configurations",
                "db_table": "widget_configurations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shop", "is_active"], name="widget_conf_shop_id_fa382b_idx"
                    )
                ],
            },
        ),
    ]
