# Generated by Django 5.2.8 on 2026-01-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="widgetconfiguration",
            name="banner_image",
        ),
        migrations.AddField(
            model_name="widgetconfiguration",
            name="banner_image_url",
            field=models.TextField(
                blank=True, default="", help_text="Banner image URL (overrides shop cover image)"
            ),
        ),
        migrations.AlterField(
            model_name="widgetconfiguration",
            name="logo_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom logo URL (overrides shop logo if provided)",
            ),
        ),
    ]
