# Generated by Django 5.2.8 on 2025-12-22 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("schedules", "0001_initial"),
        ("services", "0001_initial"),
        ("shops", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("booking_datetime", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customer", "Customer"),
                            ("staff", "Staff"),
                            ("owner", "Owner"),
                            ("system", "System"),
                        ],
                        help_text="Who cancelled the booking",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="customers.customer",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="services.service",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="shops.shop",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member assigned to this booking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="staff.staffmember",
                    ),
                ),
                (
                    "time_slot",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional: Only set for bookings created from pre-generated TimeSlots",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking",
                        to="schedules.timeslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "db_table": "bookings",
                "ordering": ["-booking_datetime"],
                "indexes": [
                    models.Index(fields=["customer", "status"], name="bookings_custome_b789e2_idx"),
                    models.Index(
                        fields=["shop", "booking_datetime"], name="bookings_shop_id_3c9231_idx"
                    ),
                ],
            },
        ),
    ]
