# Generated by Django 5.2.8 on 2026-01-02 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("services", "0003_deal_duration_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Service booked (NULL if service was deleted)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="services.service",
            ),
        ),
    ]
