# Generated by Django 5.2.8 on 2025-12-02 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("staff", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="staff_member",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member assigned to this booking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="staff.staffmember",
            ),
        ),
    ]
