# Generated by Django 5.2.8 on 2026-01-05 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_allow_service_deletion"),
        ("customers", "0001_initial"),
        ("schedules", "0001_initial"),
        ("services", "0003_deal_duration_minutes"),
        ("shops", "0002_deal_booking_support"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                help_text="Deal/package booked (NULL for service bookings)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="services.deal",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Duration of the booking in minutes (from service or deal duration)",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Service booked (NULL for deal bookings or if service was deleted)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="staff_member",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member assigned to this booking (NULL for deal bookings)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="staff.staffmember",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["deal", "booking_datetime"], name="bookings_deal_id_4a528f_idx"
            ),
        ),
    ]
