# Generated by Django 5.2.8 on 2025-12-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_staff_member"),
        ("schedules", "0002_timeslot_staff_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="time_slot",
            field=models.OneToOneField(
                blank=True,
                help_text="Optional: Only set for bookings created from pre-generated TimeSlots",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking",
                to="schedules.timeslot",
            ),
        ),
    ]
