# Generated by Django 5.2.8 on 2025-12-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_time_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancelled_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("customer", "Customer"),
                    ("staff", "Staff"),
                    ("owner", "Owner"),
                    ("system", "System"),
                ],
                help_text="Who cancelled the booking",
                max_length=20,
                null=True,
            ),
        ),
    ]
