# Generated by Django 5.2.8 on 2026-01-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_deal_booking_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not Required"),
                    ("pending", "Payment Pending"),
                    ("paid", "Deposit Paid"),
                    ("refunded", "Refunded"),
                    ("failed", "Payment Failed"),
                ],
                db_index=True,
                default="pending",
                help_text="Status of advance payment (pending = awaiting payment)",
                max_length=20,
            ),
        ),
    ]
