# Generated by Django 5.2.8 on 2025-12-31 07:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.URLField(help_text="Source URL to scrape", max_length=2000)),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Detected platform (google, yelp, booksy, etc.) or empty for generic",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scraping", "Scraping"),
                            ("parsing", "Parsing with AI"),
                            ("completed", "Completed"),
                            ("confirmed", "Shop Created"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "raw_content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Raw HTML/text content scraped from the URL",
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True, help_text="Structured data extracted by AI", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", help_text="Error message if scraping failed"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client who initiated the scrape",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrape_jobs",
                        to="clients.client",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shop created from this scrape job",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scrape_jobs",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scrape Job",
                "verbose_name_plural": "Scrape Jobs",
                "db_table": "scrape_jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "status"], name="scrape_jobs_client__ab0671_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="scrape_jobs_status_841b35_idx"
                    ),
                ],
            },
        ),
    ]
