# Generated by Django 5.2.8 on 2026-01-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapejob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scraping", "Scraping"),
                    ("parsing", "Parsing with AI"),
                    ("completed", "Completed"),
                    ("creating", "Creating Shop"),
                    ("confirmed", "Shop Created"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
