# Generated by Django 5.2.8 on 2025-12-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_user_groups_user_user_permissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("client", "Client"), ("customer", "Customer"), ("staff", "Staff")],
                default="customer",
                max_length=20,
            ),
        ),
    ]
