# Generated by Django 5.2.8 on 2025-12-22 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_duration_minutes", models.IntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Schedule",
                "verbose_name_plural": "Shop Schedules",
                "db_table": "shop_schedules",
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {("shop", "day_of_week")},
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional name for the holiday (e.g., Christmas, Eid)",
                        max_length=100,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "db_table": "shop_holidays",
                "ordering": ["date"],
                "unique_together": {("shop", "date")},
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("start_datetime", models.DateTimeField(db_index=True)),
                ("end_datetime", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="schedules.shopschedule",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member pre-assigned to this time slot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_slots",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
                "db_table": "time_slots",
                "ordering": ["start_datetime"],
                "indexes": [
                    models.Index(
                        fields=["schedule", "start_datetime", "status"],
                        name="time_slots_schedul_1cc707_idx",
                    )
                ],
            },
        ),
    ]
