# Generated by Django 5.2.8 on 2025-12-02 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="staff_member",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member pre-assigned to this time slot",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_slots",
                to="staff.staffmember",
            ),
        ),
    ]
