# Generated by Django 5.2.8 on 2025-12-15 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_timeslot_staff_member'),
        ('shops', '0003_shop_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(blank=True, default='', help_text='Optional name for the holiday (e.g., Christmas, Eid)', max_length=100)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'shop_holidays',
                'ordering': ['date'],
                'unique_together': {('shop', 'date')},
            },
        ),
    ]
