# Generated by Django 5.2.8 on 2025-12-22 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmation", "Booking Confirmation"),
                            ("booking_cancellation", "Booking Cancellation"),
                            ("booking_reschedule", "Booking Rescheduled"),
                            ("booking_reminder_1day", "Booking Reminder (1 Day)"),
                            ("booking_reminder_1hour", "Booking Reminder (1 Hour)"),
                            ("staff_assignment", "Staff Assignment Changed"),
                            ("shop_holiday", "Shop Holiday"),
                            ("new_booking", "New Booking (for staff/client)"),
                            ("payment_success", "Payment Successful"),
                            ("payment_failed", "Payment Failed"),
                            ("system", "System Notification"),
                            ("payment", "Payment Notification"),
                        ],
                        default="system",
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("related_object_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailNotificationLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmation", "Booking Confirmation"),
                            ("booking_cancellation", "Booking Cancellation"),
                            ("booking_reschedule", "Booking Rescheduled"),
                            ("booking_reminder_1day", "Booking Reminder (1 Day)"),
                            ("booking_reminder_1hour", "Booking Reminder (1 Hour)"),
                            ("staff_assignment", "Staff Assignment Changed"),
                            ("shop_holiday", "Shop Holiday"),
                            ("new_booking", "New Booking (for staff/client)"),
                            ("payment_success", "Payment Successful"),
                            ("payment_failed", "Payment Failed"),
                            ("system", "System Notification"),
                            ("payment", "Payment Notification"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("recipient_email", models.EmailField(db_index=True, max_length=254)),
                ("recipient_name", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("mailgun_message_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="bookings.booking",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related in-app notification if exists",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Notification Log",
                "verbose_name_plural": "Email Notification Logs",
                "db_table": "email_notification_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "email_booking_confirmation",
                    models.BooleanField(
                        default=True, help_text="Receive email when booking is confirmed"
                    ),
                ),
                (
                    "email_booking_cancellation",
                    models.BooleanField(
                        default=True, help_text="Receive email when booking is cancelled"
                    ),
                ),
                (
                    "email_booking_reschedule",
                    models.BooleanField(
                        default=True, help_text="Receive email when booking is rescheduled"
                    ),
                ),
                (
                    "email_booking_reminder",
                    models.BooleanField(
                        default=True, help_text="Receive reminder emails before appointments"
                    ),
                ),
                (
                    "email_staff_assignment",
                    models.BooleanField(
                        default=True, help_text="Receive email when staff member is changed"
                    ),
                ),
                (
                    "email_shop_holiday",
                    models.BooleanField(
                        default=True, help_text="Receive email about shop holiday closures"
                    ),
                ),
                (
                    "email_marketing",
                    models.BooleanField(
                        default=False, help_text="Receive marketing and promotional emails"
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(default=True, help_text="Enable in-app notifications"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="FCMDevice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "fcm_token",
                    models.CharField(
                        help_text="Firebase Cloud Messaging device token",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android"), ("web", "Web")],
                        default="web",
                        max_length=20,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional device name for identification",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Set to False if token is invalid or unregistered"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FCM Device",
                "verbose_name_plural": "FCM Devices",
                "db_table": "fcm_devices",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="fcm_devices_user_id_a9778f_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "is_read"], name="notificatio_user_id_a4dd5c_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["notification_type"], name="notificatio_notific_19df93_idx"),
        ),
        migrations.AddIndex(
            model_name="emailnotificationlog",
            index=models.Index(
                fields=["email_type", "status"], name="email_notif_email_t_3c583b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailnotificationlog",
            index=models.Index(
                fields=["booking", "email_type"], name="email_notif_booking_b400a3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailnotificationlog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("booking__isnull", False)),
                fields=("booking", "email_type", "recipient_email"),
                name="unique_booking_email_notification",
            ),
        ),
    ]
