# Generated by Django 5.2.8 on 2025-12-15 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_time_slot"),
        ("notifications", "0002_update_user_fk_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNotificationLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmation", "Booking Confirmation"),
                            ("booking_cancellation", "Booking Cancellation"),
                            ("booking_reschedule", "Booking Rescheduled"),
                            ("booking_reminder_1day", "Booking Reminder (1 Day)"),
                            ("booking_reminder_1hour", "Booking Reminder (1 Hour)"),
                            ("staff_assignment", "Staff Assignment Changed"),
                            ("shop_holiday", "Shop Holiday"),
                            ("system", "System Notification"),
                            ("payment", "Payment Notification"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("recipient_email", models.EmailField(db_index=True, max_length=254)),
                ("recipient_name", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("mailgun_message_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Email Notification Log",
                "verbose_name_plural": "Email Notification Logs",
                "db_table": "email_notification_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "email_booking_confirmation",
                    models.BooleanField(
                        default=True, help_text="Receive email when booking is confirmed"
                    ),
                ),
                (
                    "email_booking_cancellation",
                    models.BooleanField(
                        default=True, help_text="Receive email when booking is cancelled"
                    ),
                ),
                (
                    "email_booking_reschedule",
                    models.BooleanField(
                        default=True, help_text="Receive email when booking is rescheduled"
                    ),
                ),
                (
                    "email_booking_reminder",
                    models.BooleanField(
                        default=True, help_text="Receive reminder emails before appointments"
                    ),
                ),
                (
                    "email_staff_assignment",
                    models.BooleanField(
                        default=True, help_text="Receive email when staff member is changed"
                    ),
                ),
                (
                    "email_shop_holiday",
                    models.BooleanField(
                        default=True, help_text="Receive email about shop holiday closures"
                    ),
                ),
                (
                    "email_marketing",
                    models.BooleanField(
                        default=False, help_text="Receive marketing and promotional emails"
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(default=True, help_text="Enable in-app notifications"),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_confirmation", "Booking Confirmation"),
                    ("booking_cancellation", "Booking Cancellation"),
                    ("booking_reschedule", "Booking Rescheduled"),
                    ("booking_reminder_1day", "Booking Reminder (1 Day)"),
                    ("booking_reminder_1hour", "Booking Reminder (1 Hour)"),
                    ("staff_assignment", "Staff Assignment Changed"),
                    ("shop_holiday", "Shop Holiday"),
                    ("system", "System Notification"),
                    ("payment", "Payment Notification"),
                ],
                default="system",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["notification_type"], name="notificatio_notific_19df93_idx"),
        ),
        migrations.AddField(
            model_name="emailnotificationlog",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_logs",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="emailnotificationlog",
            name="notification",
            field=models.ForeignKey(
                blank=True,
                help_text="Related in-app notification if exists",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_logs",
                to="notifications.notification",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="emailnotificationlog",
            index=models.Index(
                fields=["email_type", "status"], name="email_notif_email_t_3c583b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailnotificationlog",
            index=models.Index(
                fields=["booking", "email_type"], name="email_notif_booking_b400a3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailnotificationlog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("booking__isnull", False)),
                fields=("booking", "email_type", "recipient_email"),
                name="unique_booking_email_notification",
            ),
        ),
    ]
