# Generated by Django 5.2.8 on 2025-12-17 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_emailnotificationlog_notificationpreference_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailnotificationlog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("booking_confirmation", "Booking Confirmation"),
                    ("booking_cancellation", "Booking Cancellation"),
                    ("booking_reschedule", "Booking Rescheduled"),
                    ("booking_reminder_1day", "Booking Reminder (1 Day)"),
                    ("booking_reminder_1hour", "Booking Reminder (1 Hour)"),
                    ("staff_assignment", "Staff Assignment Changed"),
                    ("shop_holiday", "Shop Holiday"),
                    ("new_booking", "New Booking (for staff/client)"),
                    ("payment_success", "Payment Successful"),
                    ("payment_failed", "Payment Failed"),
                    ("system", "System Notification"),
                    ("payment", "Payment Notification"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_confirmation", "Booking Confirmation"),
                    ("booking_cancellation", "Booking Cancellation"),
                    ("booking_reschedule", "Booking Rescheduled"),
                    ("booking_reminder_1day", "Booking Reminder (1 Day)"),
                    ("booking_reminder_1hour", "Booking Reminder (1 Hour)"),
                    ("staff_assignment", "Staff Assignment Changed"),
                    ("shop_holiday", "Shop Holiday"),
                    ("new_booking", "New Booking (for staff/client)"),
                    ("payment_success", "Payment Successful"),
                    ("payment_failed", "Payment Failed"),
                    ("system", "System Notification"),
                    ("payment", "Payment Notification"),
                ],
                default="system",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="FCMDevice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "fcm_token",
                    models.CharField(
                        help_text="Firebase Cloud Messaging device token",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android"), ("web", "Web")],
                        default="web",
                        max_length=20,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional device name for identification",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Set to False if token is invalid or unregistered"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FCM Device",
                "verbose_name_plural": "FCM Devices",
                "db_table": "fcm_devices",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="fcm_devices_user_id_a9778f_idx"
                    )
                ],
            },
        ),
    ]
